# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.fetch_logs_log_length_not_found_error import FetchLogsLogLengthNotFoundError  # noqa: E501

class TestFetchLogsLogLengthNotFoundError(unittest.TestCase):
    """FetchLogsLogLengthNotFoundError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchLogsLogLengthNotFoundError:
        """Test FetchLogsLogLengthNotFoundError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchLogsLogLengthNotFoundError`
        """
        model = FetchLogsLogLengthNotFoundError()  # noqa: E501
        if include_optional:
            return FetchLogsLogLengthNotFoundError(
                status = 404,
                type = 'log',
                id = 1001
            )
        else:
            return FetchLogsLogLengthNotFoundError(
                status = 404,
                type = 'log',
                id = 1001,
        )
        """

    def testFetchLogsLogLengthNotFoundError(self):
        """Test FetchLogsLogLengthNotFoundError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
