# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from _warg_client.api.content_api import ContentApi  # noqa: E501


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_content_sources(self) -> None:
        """Test case for get_content_sources

        Get content sources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
