# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.ledger_sources_response import LedgerSourcesResponse  # noqa: E501

class TestLedgerSourcesResponse(unittest.TestCase):
    """LedgerSourcesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LedgerSourcesResponse:
        """Test LedgerSourcesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LedgerSourcesResponse`
        """
        model = LedgerSourcesResponse()  # noqa: E501
        if include_optional:
            return LedgerSourcesResponse(
                hash_algorithm = 'sha256',
                sources = [
                    _warg_client.models.ledger_sources_response_sources_inner.LedgerSourcesResponse_sources_inner(
                        first_registry_index = 0, 
                        last_registry_index = 999, 
                        url = 'http://registry.example.com/ledger/0', 
                        content_type = 'application/vnd.warg.ledger.packed', 
                        accept_ranges = True, )
                    ]
            )
        else:
            return LedgerSourcesResponse(
        )
        """

    def testLedgerSourcesResponse(self):
        """Test LedgerSourcesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
