# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.http_upload import HttpUpload  # noqa: E501

class TestHttpUpload(unittest.TestCase):
    """HttpUpload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpUpload:
        """Test HttpUpload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpUpload`
        """
        model = HttpUpload()  # noqa: E501
        if include_optional:
            return HttpUpload(
                type = 'http',
                method = 'POST',
                url = 'https://example.com/contents.wasm',
                headers = _warg_client.models.http_upload_headers.HttpUpload_headers(
                    authorization = 'Bearer cn389ncoiwuencr', 
                    content_type = 'application/wasm', )
            )
        else:
            return HttpUpload(
                type = 'http',
                method = 'POST',
                url = 'https://example.com/contents.wasm',
        )
        """

    def testHttpUpload(self):
        """Test HttpUpload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
