# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.bundle_failure_error import BundleFailureError  # noqa: E501

class TestBundleFailureError(unittest.TestCase):
    """BundleFailureError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BundleFailureError:
        """Test BundleFailureError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BundleFailureError`
        """
        model = BundleFailureError()  # noqa: E501
        if include_optional:
            return BundleFailureError(
                status = 422,
                reason = 'failure',
                message = 'bundle must contain proofs for the same root'
            )
        else:
            return BundleFailureError(
                status = 422,
                reason = 'failure',
                message = 'bundle must contain proofs for the same root',
        )
        """

    def testBundleFailureError(self):
        """Test BundleFailureError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
