# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.package_record import PackageRecord  # noqa: E501

class TestPackageRecord(unittest.TestCase):
    """PackageRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageRecord:
        """Test PackageRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageRecord`
        """
        model = PackageRecord()  # noqa: E501
        if include_optional:
            return PackageRecord(
                record_id = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                state = 'published',
                missing_content = {sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773={upload=[{type=http, method=POST, url=https://example.com/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773}]}},
                reason = 'the first entry of the log is not `init`',
                registry_index = 56
            )
        else:
            return PackageRecord(
                record_id = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                state = 'published',
                missing_content = {sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773={upload=[{type=http, method=POST, url=https://example.com/7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773}]}},
                reason = 'the first entry of the log is not `init`',
                registry_index = 56,
        )
        """

    def testPackageRecord(self):
        """Test PackageRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
