# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from _warg_client.api.ledger_api import LedgerApi  # noqa: E501


class TestLedgerApi(unittest.TestCase):
    """LedgerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LedgerApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_ledger_sources(self) -> None:
        """Test case for get_ledger_sources

        Fetch ledger sources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
