# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.package_not_included_error import PackageNotIncludedError  # noqa: E501

class TestPackageNotIncludedError(unittest.TestCase):
    """PackageNotIncludedError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageNotIncludedError:
        """Test PackageNotIncludedError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageNotIncludedError`
        """
        model = PackageNotIncludedError()  # noqa: E501
        if include_optional:
            return PackageNotIncludedError(
                status = 422,
                reason = 'packageNotIncluded',
                log_id = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c'
            )
        else:
            return PackageNotIncludedError(
                status = 422,
                reason = 'packageNotIncluded',
                log_id = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
        )
        """

    def testPackageNotIncludedError(self):
        """Test PackageNotIncludedError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
