# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.timestamped_checkpoint import TimestampedCheckpoint  # noqa: E501

class TestTimestampedCheckpoint(unittest.TestCase):
    """TimestampedCheckpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimestampedCheckpoint:
        """Test TimestampedCheckpoint
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimestampedCheckpoint`
        """
        model = TimestampedCheckpoint()  # noqa: E501
        if include_optional:
            return TimestampedCheckpoint(
                log_length = 42,
                log_root = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                map_root = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                timestamp = 1692035502
            )
        else:
            return TimestampedCheckpoint(
                log_length = 42,
                log_root = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                map_root = 'sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c',
                timestamp = 1692035502,
        )
        """

    def testTimestampedCheckpoint(self):
        """Test TimestampedCheckpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
