# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.ledger_sources_response_sources_inner import LedgerSourcesResponseSourcesInner  # noqa: E501

class TestLedgerSourcesResponseSourcesInner(unittest.TestCase):
    """LedgerSourcesResponseSourcesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LedgerSourcesResponseSourcesInner:
        """Test LedgerSourcesResponseSourcesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LedgerSourcesResponseSourcesInner`
        """
        model = LedgerSourcesResponseSourcesInner()  # noqa: E501
        if include_optional:
            return LedgerSourcesResponseSourcesInner(
                first_registry_index = 0,
                last_registry_index = 999,
                url = 'http://registry.example.com/ledger/0',
                content_type = 'application/vnd.warg.ledger.packed',
                accept_ranges = True
            )
        else:
            return LedgerSourcesResponseSourcesInner(
                first_registry_index = 0,
                last_registry_index = 999,
                url = 'http://registry.example.com/ledger/0',
                content_type = 'application/vnd.warg.ledger.packed',
        )
        """

    def testLedgerSourcesResponseSourcesInner(self):
        """Test LedgerSourcesResponseSourcesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
