# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from _warg_client.api.fetch_api import FetchApi  # noqa: E501


class TestFetchApi(unittest.TestCase):
    """FetchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FetchApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_fetch_logs(self) -> None:
        """Test case for fetch_logs

        Fetch registry logs  # noqa: E501
        """
        pass

    def test_fetch_names(self) -> None:
        """Test case for fetch_names

        Fetch package names  # noqa: E501
        """
        pass

    def test_get_checkpoint(self) -> None:
        """Test case for get_checkpoint

        Fetch latest registry checkpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
