# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.fetch_warning import FetchWarning  # noqa: E501

class TestFetchWarning(unittest.TestCase):
    """FetchWarning unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchWarning:
        """Test FetchWarning
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchWarning`
        """
        model = FetchWarning()  # noqa: E501
        if include_optional:
            return FetchWarning(
                message = ''
            )
        else:
            return FetchWarning(
        )
        """

    def testFetchWarning(self):
        """Test FetchWarning"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
