# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.fetch_package_names_request import FetchPackageNamesRequest  # noqa: E501

class TestFetchPackageNamesRequest(unittest.TestCase):
    """FetchPackageNamesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchPackageNamesRequest:
        """Test FetchPackageNamesRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchPackageNamesRequest`
        """
        model = FetchPackageNamesRequest()  # noqa: E501
        if include_optional:
            return FetchPackageNamesRequest(
                packages = [sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773]
            )
        else:
            return FetchPackageNamesRequest(
                packages = [sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded9773],
        )
        """

    def testFetchPackageNamesRequest(self):
        """Test FetchPackageNamesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
