# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from _warg_client.models.prove_consistency404_response import ProveConsistency404Response  # noqa: E501

class TestProveConsistency404Response(unittest.TestCase):
    """ProveConsistency404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProveConsistency404Response:
        """Test ProveConsistency404Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProveConsistency404Response`
        """
        model = ProveConsistency404Response()  # noqa: E501
        if include_optional:
            return ProveConsistency404Response(
                status = 404,
                type = 'logLength',
                id = 56
            )
        else:
            return ProveConsistency404Response(
                status = 404,
                type = 'logLength',
                id = 56,
        )
        """

    def testProveConsistency404Response(self):
        """Test ProveConsistency404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
