# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, conbytes, constr, validator

class EnvelopeBody(BaseModel):
    """
    A signed envelope body.  # noqa: E501
    """
    key_id: constr(strict=True) = Field(default=..., alias="keyId", description="Represents a supported hash.")
    signature: constr(strict=True) = Field(default=..., description="The algorithm-prefixed bytes of the signature (base64 encoded).")
    content_bytes: Union[conbytes(strict=True, max_length=1048576), constr(strict=True, max_length=1048576)] = Field(default=..., alias="contentBytes", description="Base64-encoded bytes of the content.  The content of an envelope body is typically a serialized protocol buffer representing an operator or package record. ")
    __properties = ["keyId", "signature", "contentBytes"]

    @validator('key_id')
    def key_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9-]+:[a-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+:[a-f0-9]+$/")
        return value

    @validator('signature')
    def signature_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9-]+:(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{4}|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{2}={2})$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+:(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{4}|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{2}={2})$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EnvelopeBody:
        """Create an instance of EnvelopeBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EnvelopeBody:
        """Create an instance of EnvelopeBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EnvelopeBody.parse_obj(obj)

        _obj = EnvelopeBody.parse_obj({
            "key_id": obj.get("keyId"),
            "signature": obj.get("signature"),
            "content_bytes": obj.get("contentBytes")
        })
        return _obj


