# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, validator
from warg_openapi.models.ledger_sources_response_sources_inner import LedgerSourcesResponseSourcesInner

class LedgerSourcesResponse(BaseModel):
    """
    A response containing the registry ledger sources.  # noqa: E501
    """
    hash_algorithm: Optional[StrictStr] = Field(default=None, alias="hashAlgorithm", description="The type of hash algorithm used for log and record IDs.")
    sources: Optional[conlist(LedgerSourcesResponseSourcesInner)] = Field(default=None, description="The ledger sources.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["hashAlgorithm", "sources"]

    @validator('hash_algorithm')
    def hash_algorithm_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('sha256',):
            raise ValueError("must be one of enum values ('sha256')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LedgerSourcesResponse:
        """Create an instance of LedgerSourcesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item in self.sources:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sources'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LedgerSourcesResponse:
        """Create an instance of LedgerSourcesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LedgerSourcesResponse.parse_obj(obj)

        _obj = LedgerSourcesResponse.parse_obj({
            "hash_algorithm": obj.get("hashAlgorithm"),
            "sources": [LedgerSourcesResponseSourcesInner.from_dict(_item) for _item in obj.get("sources")] if obj.get("sources") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


