# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictBytes, StrictStr

class ProveInclusionResponse(BaseModel):
    """
    A response containing the inclusion proof bundle.  # noqa: E501
    """
    log: Union[StrictBytes, StrictStr] = Field(default=..., description="The log inclusion proof bundle.")
    map: Union[StrictBytes, StrictStr] = Field(default=..., description="The map inclusion proof bundle.")
    __properties = ["log", "map"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProveInclusionResponse:
        """Create an instance of ProveInclusionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProveInclusionResponse:
        """Create an instance of ProveInclusionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProveInclusionResponse.parse_obj(obj)

        _obj = ProveInclusionResponse.parse_obj({
            "log": obj.get("log"),
            "map": obj.get("map")
        })
        return _obj


