name: 'Wasm action'
description: 'Interact with a WebAssembly registry'
author: 'Xelato'

branding:
  icon: 'package'
  color: 'green'

inputs:

  action:
    description: "Requested action to perform: push, pull"
    required: true

  registry:
    description: "Registry domain name"
    required: true

  package:
    description: "Package specified as namespace/name@version where version is optional and in semver format."
    required: true

  path:
    description: "File path, glob syntax supported"


outputs:

  filename:
    description: "Package filename"
    value: ${{ steps.action.outputs.filename }}
  digest:
    description: "sha256 hash of the package file"
    value: ${{ steps.action.outputs.digest }}
  package:
    description: "Full package name"
    value: ${{ steps.action.outputs.package }}
  package-namespace:
    description: "Package namespace"
    value: ${{ steps.action.outputs.package-namespace }}
  package-name:
    description: "Package name"
    value: ${{ steps.action.outputs.package-name }}
  package-version:
    description: "Package version"
    value: ${{ steps.action.outputs.package-version }}

  registry:
    description: "registry domain name"
    value: ${{ steps[inputs.action].outputs.registry }}
  registry-type:
    description: "registry domain name"
    value: ${{ steps.action.outputs.registry-type }}


runs:
  using: "composite"

  steps:

    - name: Install uv
      run: |
        python -m pip install uv > /dev/null
        uv sync -q
      shell: bash

    - name:
      id: pull
      if: ${{ inputs.action == 'pull' }}
      shell: bash
      run: |
        uv run wasm-action pull \
          --registry "${{ inputs.registry }}" \
          --package "${{ inputs.package }}" \
          --path "${{ inputs.path }}" \

    - name:
      id: push
      if: ${{ inputs.action == 'push' }}
      shell: bash
      run: |
        uv run wasm-action push \
          --registry "${{ inputs.registry }}" \
          --package "${{ inputs.package }}" \
          --path "${{ inputs.path }}" \
