name: 'Wasm action'
description: 'Interact with a WebAssembly registry'
author: 'Xelato'

branding:
  icon: 'package'
  color: 'green'

inputs:

  action:
    description: "possible values: push, pull"
    required: true

  # registry
  registry:
    description: "Registry domain name"
    required: true

  # package
  namespace:
    description: "Target namespace"
    required: true
  name:
    description: "Target name"
    required: true
  version:
    description: "Version attribute (must be valid semver if specified)"

  # filename
  path:
    description: "file path, glob syntax supported, however, must resolve to a single file."


outputs:

  filename:
    description: "Package filename"
    value: ${{ steps.action.outputs.filename }}
  digest:
    description: "sha256 hash of the package file"
    value: ${{ steps.action.outputs.digest }}
  namespace:
    description: "Package namespace"
    value: ${{ steps.action.outputs.namespace }}
  name:
    description: "Package name"
    value: ${{ steps.action.outputs.name }}
  version:
    description: "Package version"
    value: ${{ steps.action.outputs.version }}

  registry:
    description: "registry domain name"
    value: ${{ steps.action.outputs.registry }}
  registry-type:
    description: "registry domain name"
    value: ${{ steps.action.outputs.registry-type }}


runs:
  using: "composite"

  steps:

    - name: Install uv
      run: |
        python -m pip install uv > /dev/null
        uv sync -q
      shell: bash

    - name: Validate
      id: validate
      shell: bash
      run: |
        uv run wasm-action action \
          --action "${{ inputs.action }}" \

    - name:
      id: action
      shell: bash
      run: |

        uv run wasm-action "${{ inputs.action }}" \
          --registry "${{ inputs.registry }}" \
          --namespace "${{ inputs.namespace }}" \
          --name "${{ inputs.name }}" \
          --version "${{ inputs.version }}" \
          --path "${{ inputs.path }}" \
