name: 'Wasm publish'
description: 'Publish a WebAssembly artifact (module/component/wit) to a supported registry'
author: 'Xelato'

branding:
  icon: 'package'
  color: 'green'

inputs:
  path:
    description: "file path, glob syntax supported, however, must resolve to a single file."
    required: true

  # package options
  namespace:
    description: "Target namespace"
    required: true
  name:
    description: "Target name"
    required: true
  version:
    description: "Version attribute (must be valid semver)"

  # registry options
  registry:
    description: "Registry domain name"
    required: true

  # modifiers
  check-existing:
    description: "Check whether an existing version already exists in the registry"
    type: boolean
    default: true

  fail-on-existing:
    description: "Whether to fail if an already existing package with the same version is found"
    type: boolean
    default: false

  override:
    description: "Whether to attempt to override an already existing version"
    type: boolean
    default: false


outputs:

  filename:
    description: "Input filename"
    value: ${{ steps.package.outputs.filename }}
  digest:
    description: "sha256 hash of the input file"
    value: ${{ steps.package.outputs.digest }}
  namespace:
    description: "Package namespace"
    value: ${{ steps.package.outputs.namespace }}
  name:
    description: "Package name"
    value: ${{ steps.package.outputs.name }}
  version:
    description: "Package version"
    value: ${{ steps.package.outputs.version }}

  registry:
    description: "registry domain name"
    value: ${{ steps.registry.outputs.registry }}
  registry-type:
    description: "registry domain name"
    value: ${{ steps.registry.outputs.registry-type }}
  oci-registry:
    description: "domain name of OCI registry"
    value: ${{ steps.registry.outputs.oci-registry }}
  oci-namespace-prefix:
    description: "Namespace prefix for OCI registry"
    value: ${{ steps.registry.outputs.oci-namespace-prefix }}
  warg-url:
    description: "URL for working with warg registry"
    value: ${{ steps.registry.outputs.warg-url }}


runs:
  using: "composite"

  steps:

    - name: Install uv
      run: |
        python -m pip install uv > /dev/null
        uv sync -q
      shell: bash

    - name: Validate package
      id: package
      shell: bash
      run: |
        uv run action.py package \
          --path "${{ inputs.path }}" \
          --namespace "${{ inputs.namespace }}" \
          --name "${{ inputs.name }}" \
          --version "${{ inputs.version }}" \

    - name: Validate registry
      id: registry
      shell: bash
      run: |
        uv run action.py registry \
          --registry "${{ inputs.registry }}"

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Warg login
      if: ${{ steps.registry.outputs.registry-type == 'warg' }}
      shell: bash
      run: |
        cargo binstall warg-cli
        uv run action.py warg config \
          --registry "${{ steps.registry.outputs.warg-url }}" \
          --keyring-backend flat-file

        uv run action.py warg key set
        uv run action.py warg key info
        warg key info
