# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist, constr, validator

class FetchPackageNamesRequest(BaseModel):
    """
    A request to fetch package names from the registry.  # noqa: E501
    """
    packages: conlist(constr(strict=True)) = Field(default=..., description="The log ID for each requested package.")
    __properties = ["packages"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FetchPackageNamesRequest:
        """Create an instance of FetchPackageNamesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FetchPackageNamesRequest:
        """Create an instance of FetchPackageNamesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FetchPackageNamesRequest.parse_obj(obj)

        _obj = FetchPackageNamesRequest.parse_obj({
            "packages": obj.get("packages")
        })
        return _obj


