# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr, validator

class FetchLogsLogLengthNotFoundError(BaseModel):
    """
    FetchLogsLogLengthNotFoundError
    """
    status: StrictInt = Field(default=..., description="The HTTP status code for the error.")
    type: StrictStr = Field(default=..., description="The type of entity that was not found.")
    id: StrictInt = Field(default=..., description="The log length that was not found.")
    __properties = ["status", "type", "id"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('logLength',):
            raise ValueError("must be one of enum values ('logLength')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FetchLogsLogLengthNotFoundError:
        """Create an instance of FetchLogsLogLengthNotFoundError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FetchLogsLogLengthNotFoundError:
        """Create an instance of FetchLogsLogLengthNotFoundError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FetchLogsLogLengthNotFoundError.parse_obj(obj)

        _obj = FetchLogsLogLengthNotFoundError.parse_obj({
            "status": obj.get("status"),
            "type": obj.get("type"),
            "id": obj.get("id")
        })
        return _obj


