# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictStr, constr, validator

from typing import Optional

from warg_openapi.models.package_record import PackageRecord
from warg_openapi.models.publish_package_record_request import PublishPackageRecordRequest

from warg_openapi.api_client import ApiClient
from warg_openapi.api_response import ApiResponse
from warg_openapi.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class PackageApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def get_package_record(self, log_id : Annotated[constr(strict=True), Field(..., description="The package log identifier.")], record_id : Annotated[constr(strict=True), Field(..., description="The record identifier.")], warg_registry : Annotated[Optional[StrictStr], Field(description="If present and supported, this registry responds on behalf of the other registry specified in this header value.")] = None, **kwargs) -> PackageRecord:  # noqa: E501
        """Get package record status  # noqa: E501

        Gets package record status from the registry.  A package record is in one of the following states:   * `sourcing`: The package record needs content sources.   * `processing`: The package record is being processed.   * `rejected`: The package record was rejected.   * `published`: The package record was published to the log.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_package_record(log_id, record_id, warg_registry, async_req=True)
        >>> result = thread.get()

        :param log_id: The package log identifier. (required)
        :type log_id: str
        :param record_id: The record identifier. (required)
        :type record_id: str
        :param warg_registry: If present and supported, this registry responds on behalf of the other registry specified in this header value.
        :type warg_registry: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PackageRecord
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_package_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_package_record_with_http_info(log_id, record_id, warg_registry, **kwargs)  # noqa: E501

    @validate_arguments
    def get_package_record_with_http_info(self, log_id : Annotated[constr(strict=True), Field(..., description="The package log identifier.")], record_id : Annotated[constr(strict=True), Field(..., description="The record identifier.")], warg_registry : Annotated[Optional[StrictStr], Field(description="If present and supported, this registry responds on behalf of the other registry specified in this header value.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Get package record status  # noqa: E501

        Gets package record status from the registry.  A package record is in one of the following states:   * `sourcing`: The package record needs content sources.   * `processing`: The package record is being processed.   * `rejected`: The package record was rejected.   * `published`: The package record was published to the log.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_package_record_with_http_info(log_id, record_id, warg_registry, async_req=True)
        >>> result = thread.get()

        :param log_id: The package log identifier. (required)
        :type log_id: str
        :param record_id: The record identifier. (required)
        :type record_id: str
        :param warg_registry: If present and supported, this registry responds on behalf of the other registry specified in this header value.
        :type warg_registry: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PackageRecord, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'log_id',
            'record_id',
            'warg_registry'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_package_record" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['log_id'] is not None:
            _path_params['logId'] = _params['log_id']

        if _params['record_id'] is not None:
            _path_params['recordId'] = _params['record_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['warg_registry'] is not None:
            _header_params['Warg-Registry'] = _params['warg_registry']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "PackageRecord",
            '404': "GetPackageRecord404Response",
        }

        return self.api_client.call_api(
            '/package/{logId}/record/{recordId}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def publish_package_record(self, log_id : Annotated[constr(strict=True), Field(..., description="The package log identifier.")], publish_package_record_request : PublishPackageRecordRequest, warg_registry : Annotated[Optional[StrictStr], Field(description="If present and supported, this registry responds on behalf of the other registry specified in this header value.")] = None, **kwargs) -> PackageRecord:  # noqa: E501
        """Publish package record  # noqa: E501

        Attempts to publish a new record to a package log.  Publishing package records is an asynchronous operation.  The record must be signed by a key that is authorized to modify the package log.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.publish_package_record(log_id, publish_package_record_request, warg_registry, async_req=True)
        >>> result = thread.get()

        :param log_id: The package log identifier. (required)
        :type log_id: str
        :param publish_package_record_request: (required)
        :type publish_package_record_request: PublishPackageRecordRequest
        :param warg_registry: If present and supported, this registry responds on behalf of the other registry specified in this header value.
        :type warg_registry: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PackageRecord
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the publish_package_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.publish_package_record_with_http_info(log_id, publish_package_record_request, warg_registry, **kwargs)  # noqa: E501

    @validate_arguments
    def publish_package_record_with_http_info(self, log_id : Annotated[constr(strict=True), Field(..., description="The package log identifier.")], publish_package_record_request : PublishPackageRecordRequest, warg_registry : Annotated[Optional[StrictStr], Field(description="If present and supported, this registry responds on behalf of the other registry specified in this header value.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Publish package record  # noqa: E501

        Attempts to publish a new record to a package log.  Publishing package records is an asynchronous operation.  The record must be signed by a key that is authorized to modify the package log.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.publish_package_record_with_http_info(log_id, publish_package_record_request, warg_registry, async_req=True)
        >>> result = thread.get()

        :param log_id: The package log identifier. (required)
        :type log_id: str
        :param publish_package_record_request: (required)
        :type publish_package_record_request: PublishPackageRecordRequest
        :param warg_registry: If present and supported, this registry responds on behalf of the other registry specified in this header value.
        :type warg_registry: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PackageRecord, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'log_id',
            'publish_package_record_request',
            'warg_registry'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method publish_package_record" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['log_id'] is not None:
            _path_params['logId'] = _params['log_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        if _params['warg_registry'] is not None:
            _header_params['Warg-Registry'] = _params['warg_registry']

        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['publish_package_record_request'] is not None:
            _body_params = _params['publish_package_record_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '202': "PackageRecord",
            '401': "Error",
            '404': "PublishPackageRecord404Response",
            '409': "PublishPackageRecord409Response",
            '422': "Error",
            '501': "Error",
        }

        return self.api_client.call_api(
            '/package/{logId}/record', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
