# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr, constr, validator

class GetPackageRecord404Response(BaseModel):
    """
    GetPackageRecord404Response
    """
    status: StrictInt = Field(default=..., description="The HTTP status code for the error.")
    type: StrictStr = Field(default=..., description="The type of entity that was not found.")
    id: constr(strict=True) = Field(default=..., description="Represents a supported hash.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["status", "type", "id"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('log', 'record',):
            raise ValueError("must be one of enum values ('log', 'record')")
        return value

    @validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9-]+:[a-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+:[a-f0-9]+$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetPackageRecord404Response:
        """Create an instance of GetPackageRecord404Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetPackageRecord404Response:
        """Create an instance of GetPackageRecord404Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetPackageRecord404Response.parse_obj(obj)

        _obj = GetPackageRecord404Response.parse_obj({
            "status": obj.get("status"),
            "type": obj.get("type"),
            "id": obj.get("id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


