# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class HttpUploadHeaders(BaseModel):
    """
    The HTTP headers for upload request. Header name is required to be all lowercase.  # noqa: E501
    """
    authorization: Optional[StrictStr] = Field(default=None, description="Authorization header.")
    content_type: Optional[StrictStr] = Field(default=None, alias="content-type", description="Content type header.")
    __properties = ["authorization", "content-type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HttpUploadHeaders:
        """Create an instance of HttpUploadHeaders from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HttpUploadHeaders:
        """Create an instance of HttpUploadHeaders from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HttpUploadHeaders.parse_obj(obj)

        _obj = HttpUploadHeaders.parse_obj({
            "authorization": obj.get("authorization"),
            "content_type": obj.get("content-type")
        })
        return _obj


