# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, constr, validator

class ProcessingRecord(BaseModel):
    """
    A record that is being processed.  # noqa: E501
    """
    record_id: constr(strict=True) = Field(default=..., alias="recordId", description="Represents a supported hash.")
    state: StrictStr = Field(default=..., description="The state of the package record.")
    __properties = ["recordId", "state"]

    @validator('record_id')
    def record_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9-]+:[a-f0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9-]+:[a-f0-9]+$/")
        return value

    @validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('processing',):
            raise ValueError("must be one of enum values ('processing')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProcessingRecord:
        """Create an instance of ProcessingRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProcessingRecord:
        """Create an instance of ProcessingRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProcessingRecord.parse_obj(obj)

        _obj = ProcessingRecord.parse_obj({
            "record_id": obj.get("recordId"),
            "state": obj.get("state")
        })
        return _obj


