# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from warg_openapi.models.bundle_failure_error import BundleFailureError
from warg_openapi.models.incorrect_proof_error import IncorrectProofError
from warg_openapi.models.package_not_included_error import PackageNotIncludedError
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

PROVEINCLUSION422RESPONSE_ONE_OF_SCHEMAS = ["BundleFailureError", "IncorrectProofError", "PackageNotIncludedError"]

class ProveInclusion422Response(BaseModel):
    """
    ProveInclusion422Response
    """
    # data type: PackageNotIncludedError
    oneof_schema_1_validator: Optional[PackageNotIncludedError] = None
    # data type: IncorrectProofError
    oneof_schema_2_validator: Optional[IncorrectProofError] = None
    # data type: BundleFailureError
    oneof_schema_3_validator: Optional[BundleFailureError] = None
    if TYPE_CHECKING:
        actual_instance: Union[BundleFailureError, IncorrectProofError, PackageNotIncludedError]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(PROVEINCLUSION422RESPONSE_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    discriminator_value_class_map = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ProveInclusion422Response.construct()
        error_messages = []
        match = 0
        # validate data type: PackageNotIncludedError
        if not isinstance(v, PackageNotIncludedError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PackageNotIncludedError`")
        else:
            match += 1
        # validate data type: IncorrectProofError
        if not isinstance(v, IncorrectProofError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IncorrectProofError`")
        else:
            match += 1
        # validate data type: BundleFailureError
        if not isinstance(v, BundleFailureError):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BundleFailureError`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ProveInclusion422Response with oneOf schemas: BundleFailureError, IncorrectProofError, PackageNotIncludedError. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ProveInclusion422Response with oneOf schemas: BundleFailureError, IncorrectProofError, PackageNotIncludedError. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ProveInclusion422Response:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ProveInclusion422Response:
        """Returns the object represented by the json string"""
        instance = ProveInclusion422Response.construct()
        error_messages = []
        match = 0

        # use oneOf discriminator to lookup the data type
        _data_type = json.loads(json_str).get("reason")
        if not _data_type:
            raise ValueError("Failed to lookup data type from the field `reason` in the input.")

        # check if data type is `BundleFailureError`
        if _data_type == "failure":
            instance.actual_instance = BundleFailureError.from_json(json_str)
            return instance

        # check if data type is `IncorrectProofError`
        if _data_type == "incorrectProof":
            instance.actual_instance = IncorrectProofError.from_json(json_str)
            return instance

        # check if data type is `PackageNotIncludedError`
        if _data_type == "packageNotIncluded":
            instance.actual_instance = PackageNotIncludedError.from_json(json_str)
            return instance

        # check if data type is `BundleFailureError`
        if _data_type == "BundleFailureError":
            instance.actual_instance = BundleFailureError.from_json(json_str)
            return instance

        # check if data type is `IncorrectProofError`
        if _data_type == "IncorrectProofError":
            instance.actual_instance = IncorrectProofError.from_json(json_str)
            return instance

        # check if data type is `PackageNotIncludedError`
        if _data_type == "PackageNotIncludedError":
            instance.actual_instance = PackageNotIncludedError.from_json(json_str)
            return instance

        # deserialize data into PackageNotIncludedError
        try:
            instance.actual_instance = PackageNotIncludedError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IncorrectProofError
        try:
            instance.actual_instance = IncorrectProofError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BundleFailureError
        try:
            instance.actual_instance = BundleFailureError.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ProveInclusion422Response with oneOf schemas: BundleFailureError, IncorrectProofError, PackageNotIncludedError. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ProveInclusion422Response with oneOf schemas: BundleFailureError, IncorrectProofError, PackageNotIncludedError. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


