# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, StrictStr, validator

class PublishedRecord(BaseModel):
    """
    A record that has been published to the log.  # noqa: E501
    """
    state: StrictStr = Field(default=..., description="The state of the package record.")
    registry_index: StrictInt = Field(default=..., alias="registryIndex", description="The index of the record in the registry log.")
    __properties = ["state", "registryIndex"]

    @validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('published',):
            raise ValueError("must be one of enum values ('published')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PublishedRecord:
        """Create an instance of PublishedRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PublishedRecord:
        """Create an instance of PublishedRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PublishedRecord.parse_obj(obj)

        _obj = PublishedRecord.parse_obj({
            "state": obj.get("state"),
            "registry_index": obj.get("registryIndex")
        })
        return _obj


