# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from warg_openapi.models.http_get import HttpGet  # noqa: E501

class TestHttpGet(unittest.TestCase):
    """HttpGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpGet:
        """Test HttpGet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpGet`
        """
        model = HttpGet()  # noqa: E501
        if include_optional:
            return HttpGet(
                type = 'httpGet',
                url = 'https://example.com/contents.wasm',
                accept_ranges = True,
                size = 1024
            )
        else:
            return HttpGet(
                type = 'httpGet',
                url = 'https://example.com/contents.wasm',
        )
        """

    def testHttpGet(self):
        """Test HttpGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
