# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warg_openapi.api.proof_api import ProofApi  # noqa: E501


class TestProofApi(unittest.TestCase):
    """ProofApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProofApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_prove_consistency(self) -> None:
        """Test case for prove_consistency

        Prove registry checkpoint consistency  # noqa: E501
        """
        pass

    def test_prove_inclusion(self) -> None:
        """Test case for prove_inclusion

        Prove log leaf inclusion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
