# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warg_openapi.api.monitor_api import MonitorApi  # noqa: E501


class TestMonitorApi(unittest.TestCase):
    """MonitorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MonitorApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_verify_checkpoint(self) -> None:
        """Test case for verify_checkpoint

        Verify registry checkpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
