# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from warg_openapi.models.fetch_logs_response import FetchLogsResponse  # noqa: E501

class TestFetchLogsResponse(unittest.TestCase):
    """FetchLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchLogsResponse:
        """Test FetchLogsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchLogsResponse`
        """
        model = FetchLogsResponse()  # noqa: E501
        if include_optional:
            return FetchLogsResponse(
                more = False,
                operator = [
                    null
                    ],
                warnings = [
                    warg_openapi.models.fetch_warning.FetchWarning(
                        message = '', )
                    ],
                packages = {sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730=[{contentBytes=ZXhhbXBsZQ==, keyId=sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730, signature=ecdsa-p256:MEUCIQCzWZBW6ux9LecP66Y+hjmLZTP/hZVz7puzlPTXcRT2wwIgQZO7nxP0nugtw18MwHZ26ROFWcJmgCtKOguK031Y1D0=, registryIndex=101, fetchToken=sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730}, {contentBytes=ZXhhbXBsZQ==, keyId=sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730, signature=ecdsa-p256:MEUCIQCzWZBW6ux9LecP66Y+hjmLZTP/hZVz7puzlPTXcRT2wwIgQZO7nxP0nugtw18MwHZ26ROFWcJmgCtKOguK031Y1D0=, registryIndex=305, fetchToken=sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c}], sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c=[{contentBytes=ZXhhbXBsZQ==, keyId=sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730, signature=ecdsa-p256:MEUCIQCzWZBW6ux9LecP66Y+hjmLZTP/hZVz7puzlPTXcRT2wwIgQZO7nxP0nugtw18MwHZ26ROFWcJmgCtKOguK031Y1D0=, registryIndex=732, fetchToken=sha256:ygdb4e8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae00a8y}]}
            )
        else:
            return FetchLogsResponse(
        )
        """

    def testFetchLogsResponse(self):
        """Test FetchLogsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
