# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from warg_openapi.models.publish_package_record409_response import PublishPackageRecord409Response  # noqa: E501

class TestPublishPackageRecord409Response(unittest.TestCase):
    """PublishPackageRecord409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishPackageRecord409Response:
        """Test PublishPackageRecord409Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishPackageRecord409Response`
        """
        model = PublishPackageRecord409Response()  # noqa: E501
        if include_optional:
            return PublishPackageRecord409Response(
                status = 409,
                type = 'namespace',
                id = ''
            )
        else:
            return PublishPackageRecord409Response(
                status = 409,
                type = 'namespace',
                id = '',
        )
        """

    def testPublishPackageRecord409Response(self):
        """Test PublishPackageRecord409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
