# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from warg_openapi.models.published_record import PublishedRecord  # noqa: E501

class TestPublishedRecord(unittest.TestCase):
    """PublishedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishedRecord:
        """Test PublishedRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishedRecord`
        """
        model = PublishedRecord()  # noqa: E501
        if include_optional:
            return PublishedRecord(
                state = 'published',
                registry_index = 56
            )
        else:
            return PublishedRecord(
                state = 'published',
                registry_index = 56,
        )
        """

    def testPublishedRecord(self):
        """Test PublishedRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
