# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from warg_openapi.models.prove_consistency_response import ProveConsistencyResponse  # noqa: E501

class TestProveConsistencyResponse(unittest.TestCase):
    """ProveConsistencyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProveConsistencyResponse:
        """Test ProveConsistencyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProveConsistencyResponse`
        """
        model = ProveConsistencyResponse()  # noqa: E501
        if include_optional:
            return ProveConsistencyResponse(
                proof = 'ZXhhbXBsZQ=='
            )
        else:
            return ProveConsistencyResponse(
                proof = 'ZXhhbXBsZQ==',
        )
        """

    def testProveConsistencyResponse(self):
        """Test ProveConsistencyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
