# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warg_openapi.api.package_api import PackageApi  # noqa: E501


class TestPackageApi(unittest.TestCase):
    """PackageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PackageApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_get_package_record(self) -> None:
        """Test case for get_package_record

        Get package record status  # noqa: E501
        """
        pass

    def test_publish_package_record(self) -> None:
        """Test case for publish_package_record

        Publish package record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
