# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, validator

class HttpGet(BaseModel):
    """
    A known GET HTTP content source.  # noqa: E501
    """
    type: StrictStr = Field(default=..., description="The type of content source.")
    url: StrictStr = Field(default=..., description="The URL of the content.")
    accept_ranges: Optional[StrictBool] = Field(default=None, alias="acceptRanges", description="Flag indicating if the server accepts byte ranges with `Range` header.")
    size: Optional[StrictInt] = Field(default=None, description="Content size in bytes.")
    __properties = ["type", "url", "acceptRanges", "size"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('httpGet',):
            raise ValueError("must be one of enum values ('httpGet')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HttpGet:
        """Create an instance of HttpGet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HttpGet:
        """Create an instance of HttpGet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HttpGet.parse_obj(obj)

        _obj = HttpGet.parse_obj({
            "type": obj.get("type"),
            "url": obj.get("url"),
            "accept_ranges": obj.get("acceptRanges"),
            "size": obj.get("size")
        })
        return _obj


