# coding: utf-8

"""
    Warg Registry API

    [warg](https://warg.io/) is an open source protocol for WebAssembly component registries. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist

class ProveInclusionRequest(BaseModel):
    """
    A request to prove the inclusion of log leafs in a checkpoint.  # noqa: E501
    """
    log_length: StrictInt = Field(default=..., alias="logLength", description="The checkpoint log length to prove the inclusion for.")
    leafs: conlist(StrictInt, max_items=1000) = Field(default=..., description="The log leaf registry log index to prove the inclusion for.")
    __properties = ["logLength", "leafs"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProveInclusionRequest:
        """Create an instance of ProveInclusionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProveInclusionRequest:
        """Create an instance of ProveInclusionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProveInclusionRequest.parse_obj(obj)

        _obj = ProveInclusionRequest.parse_obj({
            "log_length": obj.get("logLength"),
            "leafs": obj.get("leafs")
        })
        return _obj


